apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: syspass
  name: syspass-db
  labels:
    group: syspass
    app: syspass-db
spec:
  replicas: 1
  selector:
    matchLabels:
      group: syspass
      app: syspass-db
  template:
    metadata:
      labels:
        group: syspass
        app: syspass-db
    spec:
      volumes:
      - name: syspass-db-storage
        persistentVolumeClaim:
          claimName: syspass-db-claim
      containers:
      - name: syspass-db
        image: mariadb:10.2
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: syspass-secret
                key: "root-pass"
        ports:
        - containerPort: 3306
          name: syspass-db
        volumeMounts:
          - name: syspass-db-storage
            mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  namespace: syspass
  name: syspass-db
  labels:
    group: syspass
    app: syspass-db

spec:
  selector:
    group: syspass
    app: syspass-db
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      name: syspass-db