apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: syspass
  name: syspass-app
  labels:
    group: syspass
    app: syspass-app
spec:
  replicas: 1
  selector:
    matchLabels:
      group: syspass
      app: syspass-app
  template:
    metadata:
      labels:
        group: syspass
        app: syspass-app
    spec:
      containers:
      - name: syspass-app
        image: syspass/syspass:3.1.0
        imagePullPolicy: IfNotPresent
        env:
          - name: COMPOSER_EXTENSIONS
            value: syspass/plugin-authenticator:^v2.0
        ports:
        - containerPort: 80
          name: syspass-http
        - containerPort: 443
          name: syspass-https
        volumeMounts:
          - name: syspass-config
            mountPath: /var/www/html/sysPass/app/config 
          - name: syspass-backup
            mountPath: /var/www/html/sysPass/app/backup
  volumeClaimTemplates:
  - metadata:
      name: syspass-config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi

  - metadata:
      name: syspass-backup
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi

---

apiVersion: v1
kind: Service
metadata:
  namespace: syspass
  name: syspass-app
  labels:
    group: syspass
    app: syspass-app

spec:
  selector:
    group: syspass
    app: syspass-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: syspass-http
    - port: 443
      targetPort: 443
      name: syspass-https
