apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: syspass
  name: syspass-db
  labels:
    group: syspass
    app: syspass-db
spec:
  replicas: 1
  serviceName: "syspass-db"
  selector:
    matchLabels:
      group: syspass
      app: syspass-db
  template:
    metadata:
      labels:
        group: syspass
        app: syspass-db
    spec:
      containers:
      - name: syspass-db
        image: mariadb:10.2
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: syspass-secret
                key: "root-pass"
        ports:
        - containerPort: 3306
          name: syspass-db
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      storageClassName: "db"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  namespace: syspass
  name: syspass-db
  labels:
    group: syspass
    app: syspass-db

spec:
  selector:
    group: syspass
    app: syspass-db
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
      name: syspass-db