apiVersion: v1
kind: PersistentVolume
metadata:
  name: syspass
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/syspass"
