apiVersion: v1
kind: PersistentVolume
metadata:
  name: syspass-db-pv
  labels:
    type: local
spec:
  storageClassName: "db"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/syspass/db"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: syspass-app-pv
  labels:
    type: local
spec:
  storageClassName: "app"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/syspass/app"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: syspass-backup-pv
  labels:
    type: local
spec:
  storageClassName: "backup"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/syspass/backup"